name: grocery
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10
  cached_network_image: ^3.4.0
  form_field_validator: ^1.1.0
  animations: ^2.0.11
  flutter_credit_card: ^3.0.3
  lottie: ^2.7.0  # <-- Added Lottie package here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.2.3+1
  flutter_launcher_icons: ^0.13.1

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/app_logo_splash.png"
  android: true
  ios: true
  web: false

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/campusbite_logo.png
    - assets/icons/
    - assets/animations/  # <-- Added for Lottie JSON files